### ISSUE TITLE
List difference to imenu support from go-mode

### ISSUE THREAD

**Issue by dakra** [brantou/go-imenu.el#1]
I'm wondering what's the difference to the imenu support in `go-mode`.
I guess it's way simpler and has only functions and types but works fast and reliable.

**Comment by brantou** [comment]
@dakra   Use [go-outline](https://github.com/lukehoban/go-outline) to enhance imenu support, and automatically downgrade to the original implementation([go-mode.el](https://github.com/dominikh/go-mode.el/blob/120fb911f1d8038f828da85eed8aaad977dabd8c/go-mode.el#L990)) when the go-outline is unavailable or any error occurs.

**Comment by dakra** [comment]
I was more wondering what 'enhance imenu support' really is as `go-mode` already provides imenu support for type and function declarations.
Looking in the `go-outline` source I see that they have additionally `import`, `variable`, and `package`.

Closing this as it's not really an issue :)

**Comment by brantou** [comment]
@dakra go-mode.el use elisp, base [regex](https://github.com/dominikh/go-mode.el/blob/120fb911f1d8038f828da85eed8aaad977dabd8c/go-mode.el#L990).
go-imenu.el use go, base  go's package([ast/parse/token/format](https://github.com/lukehoban/go-outline/blob/e785568742524aa488d7332e7619dba87b2a8b9d/main.go#L8)).
> If you want to know more details, please click on the link above.

I think go's package is simpler, faster, and more accurate than elisp's regular expression.
